Simplify config
curationexperts-deprecated/tenejo-v1 pull request #330
Opened 2021-03-22 15:11 UTC by maxkadel

- Ensure config for solr and fedora will work outside of docker 
- Restore standard solr & fedora config patterns
- Remove outdated test comment

Co-Authored-By: Rachel Kadel <rachel.kadel@curationexperts.com>

2021-03-22 15:49 UTC, mark-dce requested changes
The urls in the new change don't seem simpler.  Instead of one possible configuration path, it seems like there are now three:
1. if SOLR_URL is configured in the environment, we just get that
2. if SOLR_URL is missing, but SOLR_DEVELOPMENT_PORT is configured , we get that substituted in
3. if neither environment variable is set, we get http://127.0.0.1/8983/solr/hydra-development

Is there a way we could do things that just allowed the first case to cover all the other permutations?

2021-03-22 15:49 UTC, mark-dce commented on config/blacklight.yml
> +  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:#{ENV.fetch('SOLR_DEVELOPMENT_PORT', 8983)}/solr/hydra-development" %>
Why can't we just ensure we have an environment variable configured - this is specifically in the development environment - isn't it possible to handle this with dot-env in either docker or local setup?

2021-03-22 15:49 UTC, mark-dce commented on config/blacklight.yml
> +  url: <%= ENV['SOLR_TEST_URL'] || "http://127.0.0.1:#{ENV.fetch('SOLR_TEST_PORT', 8985)}/solr/hydra-test" %>
Similar question as above - if we can configure a SOLR_TEST_PORT in the environment, can't we configure a SOLR_TEST URL.  

If you really need something hard-coded, it seems like this might be clearer
`<%= ENV['SOLR_TEST_URL'] || "http://127.0.0.1:8985/solr/hydra-test" %>

But I think we can configure the environment in all cases, so <%= ENV['SOLR_TEST_URL']> seems like the simpler convention to manage.

2021-03-22 15:49 UTC, mark-dce commented on docker-compose.yml
> +      FEDORA_TEST_URL: http://fedora:8080/rest
Could we just create a Docker and a non-docker section in the .env.sample and comment out the one that isn't relevant?

2021-03-23 13:11 UTC, maxkadel commented
My intention was just to bring it back to the configuration that seems to be pretty standard in Blacklight and Hyrax projects and avoid bringing in CI-only environment variables, as well as allowing for non-docker test and development.

2021-03-23 13:13 UTC, maxkadel commented on config/blacklight.yml
> +  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:#{ENV.fetch('SOLR_DEVELOPMENT_PORT', 8983)}/solr/hydra-development" %>
Simplifying this breaks the Samvera orb in CI.

2021-03-23 14:11 UTC, closed without merging