Removed "Submit your work" button from homepage.
curationexperts-deprecated/tenejo-v1 pull request #385
Opened 2021-09-09 14:18 UTC by norm0

This removes the submit work button and the terms of service only if the feature flipper for 'New UI' is turned on.

2021-09-09 14:22 UTC, maxkadel requested changes
2 requests:

- Tests! 
- Screenshots of homepage with flipper on vs. flipper off

2021-09-09 19:13 UTC, norm0 commented
New UI off![screencapture-localhost-3000-2021-09-09-14_12_58](https://user-images.githubusercontent.com/8102/132748453-9f197cee-ba99-4b85-b224-cc1a392a3b06.png)


New UI On: ![screencapture-localhost-3000-2021-09-09-14_11_30](https://user-images.githubusercontent.com/8102/132748288-479abfa2-fbe5-4138-a0aa-c3747b578a3a.png)

2021-09-12 14:47 UTC, maxkadel approved these changes

2021-09-12 15:09 UTC, maxkadel approved these changes

2021-09-12 15:09 UTC, merged